name: CaveCrawlers
version: '${version}'
main: me.lidan.cavecrawlers.CaveCrawlers
api-version: '1.20'
depend:
  - Vault
  - ProtocolLib
  - MythicMobs
softdepend:
  - PlaceholderAPI
  - LuckPerms
  - Plugman
libraries:
  - org.jdbi:jdbi3-core:3.45.0
  - org.jdbi:jdbi3-sqlobject:3.45.0
