name: CaveCrawlers
version: '${version}'
main: me.lidan.cavecrawlers.CaveCrawlers
api-version: '1.20'
depend:
  - Vault
  - ProtocolLib
  - MythicMobs
softdepend:
  - PlaceholderAPI
  - LuckPerms
  - Plugman